server:
  port: 18080

spring:
  application:
    name: seatademo-start
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&nullCatalogMeansCurrent=true&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password:
    hikari:
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: HikariDataSource
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
    alibaba:
      seata:
        tx-service-group: seatademo-start-service-group

logging:
  level:
    root: info
    org.mybatis: debug
    java.sql: debug
    org.springframework.web: trace
    io.seata: info

arthas:
  agent-id: seatademo-start
  http-port: 18090
  home: D:/Dev_Tools/arthas-3.3.7
  ip: localhost
  telnet-port: 18070
  slient-init: false
  session-timeout: 10
  stat-url:

seata:
  enabled: true
  registry:
    nacos:
      cluster: default
      server-addr: localhost
  service:
    disable-global-transaction: false
    grouplist:
      default: 127.0.0.1:8091
    vgroup-mapping:
      seatademo-start-service-group: default
  tx-service-group: seatademo-start-service-group