server:
  port: 8080

spring:
  application:
    name: seatademo-start
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&nullCatalogMeansCurrent=true&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password:
    hikari:
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: HikariDataSource
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: SELECT 1

seata:
  enabled: true
  service:
    vgroupMapping:
      default_tx_group: default
    grouplist:
      default: 127.0.0.1:8091
    disable-global-transaction: false
  registry:
    type: nacos
  nacos:
    cluster: default
    server-addr: localhost
  application-id: seatademo-start
  tx-service-group: default-seata-service-group